asking for minuts in prompt, possibility of unblocking only some websites

diff --git a/unblock_communications b/unblock_communications
--- a/unblock_communications
+++ b/unblock_communications
@@ -1,14 +1,10 @@
 #!/bin/bash
 
-# TODO: +Logging (to google calendar?)
+# TODO: 
+# +Logging (to google calendar?)
 
 set -e
 
-if [ $# -ne 1 ]
-then
-    echo "usage: unblock_communications num_minutes"
-    exit
-fi
 
 int_handler()
 {
@@ -19,39 +15,53 @@ int_handler()
 }
 trap 'int_handler' INT
 
-/home/jiri/projects/scripts/block_communications
+/home/jiri/projects/scripts/block_communications > /dev/null
 
-if [ "$1" -gt "180" ]; then
-    echo "error: time interval larger than 180"
-    exit 1
-fi
-
-echo "Please wait 5 seconds. Are you sure you cannot avoid checking messages?"
-sleep 5
-while true; do
+if [ $# -eq 0 ]
+then
+    echo "Please wait 5 seconds. Are you sure you cannot avoid checking messages?"
+    # sleep 5
     # empty stdin buffer so that user cannot answer in advance
     while read -r -t 0; do read -r; done
-    read -p "Are you sure (y/n)? " yn
-    case $yn in
-        [Yy]* ) break;;
-        * ) exit;;
-    esac
-done
+    read -p "How long (in minutes)? " duration
+    if [ "$duration" -gt "180" ]; then
+        echo "error: time interval larger than 180"
+        exit 1
+    fi
+    re='^[0-9]+$'
+    if ! [[ $duration =~ $re ]] ; then
+        echo "error: Not a number" >&2; exit 1
+    fi
 
-echo "I will block you for 30 more seconds, you can still interrupt it."
-sleep 30
-# echo "Unblocked."
+    echo "I will block you for 30 more seconds, you can still interrupt it."
+    sleep 30
+    # echo "Unblocked."
 
-score_communications.sh
+    score_communications.sh
 
-sudo sed -i -r '/^[^#].*BLOCKME.*/s/^/# /g' /etc/hosts
-
-# blocking again if second argument given::
-if [ $# -eq 1 ]
-then
-    # echo "blocking again in $1 minutes"
-    echo '/home/jiri/projects/scripts/block_communications' | at now +$1 minutes 2> /dev/null
+    sudo sed -i -r '/^[^#].*BLOCKME.*/s/^/# /g' /etc/hosts
 fi
+
+if [ $# -ne 0 ]
+then
+    sleep 5
+    # empty stdin buffer so that user cannot answer in advance
+    while read -r -t 0; do read -r; done
+    read -p "How long (in minutes)? " duration
+    if [ "$duration" -gt "180" ]; then
+        echo "error: time interval larger than 180"
+        exit 1
+    fi
+    re='^[0-9]+$'
+    if ! [[ $duration =~ $re ]] ; then
+        echo "error: Not a number" >&2; exit 1
+    fi
+    echo "I will block you for 30 more seconds, you can still interrupt it."
+    sleep 30
+    sudo sed -i -r "/^[^#].*$1.*/s/^/# /g" /etc/hosts
+fi
+# echo "blocking again in $duration minutes"
+echo '/home/jiri/projects/scripts/block_communications' | at now +$duration minutes 2> /dev/null
 
 # logging:
 date '+%Y-%m-%d %H:%M:%S unblock' >> ~/.block_communications.log
